version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    command: --smallfiles
  app:
    image: mirkobrandt/pathfinder
    ports:
    - 8080:8080
    links:
    - mongodb