version: "2"
services:
  mongodb:
    image: mongo:4.0.10
    container_name: mongoserver
  app:
    image: mirkobrandt/pathfinder
    build: .
    ports:
    - 8080:8080
    depends_on:
    - mongodb